### ISSUE TITLE
icons have blue line under them in-conjunction with actual "indicator"

### ISSUE THREAD

**Issue by SwampRabbit** [nsz32/docklike-plugin#103]
Building off @davekeogh fork from the 12th, I've noticed that the icons have a blue line underneath them in-conjunction with the actual "indicator".

This just popped up with this recent version and I see some more recent commits, so I'll build again and see if it goes away.

Just wanted to post if it wasn't identified already.

<blockquote class="imgur-embed-pub" lang="en" data-id="AMZ2aop"  ><a href="//imgur.com/AMZ2aop">Ksnip Screenshot</a></blockquote>

**Comment by davekeogh** [comment]
Hey. I'm making some changes to the theme code to make it easier to work with. I probably won't be able to finish it until next weekend. There are a few graphical regressions in master at the moment.

I enabled the issue tracker on my repo because I haven't been able get in contact with nsz32 and this issue list is a mess now. Please use that one from now on.

**Comment by SwampRabbit** [comment]
@davekeogh fully understood boss, no rush at all, please take your time.  :+1: 

I'll use your issue tracker.  Hope nsz32 (Nico) is just super busy and everything with him is ok.

**Comment by SwampRabbit** [comment]
no reason to have this issue open any more, closing it as I am no longer using or testing this version of docklike, unless others believe it should be opened back up because the issue still exists.
